-- Create table
IF OBJECT_ID('IISLOG','U') IS NULL
BEGIN
CREATE TABLE [IISLOG](
[COOKIE_ID] [int] NOT NULL,
[VISIT_DATE] [date] NOT NULL,
[TRANSACTION_VALUE] [money] NOT NULL
) ON [PRIMARY]
CREATE CLUSTERED INDEX [IX_VISIT_DATE] ON [IISLOG]
([VISIT_DATE] ASC) ON [PRIMARY]
END
-- Empty the table
DELETE FROM IISLOG

-- Insert 8 million rows in batches of 5,000
DECLARE @I INT = 0
DECLARE @HITS INT = 8000000
DECLARE @BATCH_SIZE INT = 5000
DECLARE @BATCH_COUNT INT = 0

WHILE @I < @HITS
BEGIN
    BEGIN TRANSACTION
    
    SET @BATCH_COUNT = 0
    
    WHILE @BATCH_COUNT < @BATCH_SIZE AND @I < @HITS
    BEGIN
        INSERT INTO IISLOG(COOKIE_ID, VISIT_DATE, TRANSACTION_VALUE)
        SELECT 
            RAND() * @HITS / 100, -- COOKIE_ID
            DATEADD(day, CONVERT(INT, (RAND() * 365)), '20170801'), -- VISIT DATE
            CASE WHEN RAND() < 0.01 THEN RAND() * 10.0 ELSE 0.0 END -- TRANSACTION_VALUE
        
        SET @I = @I + 1
        SET @BATCH_COUNT = @BATCH_COUNT + 1
    END
    
    COMMIT TRANSACTION
    -- Optional: Print progress every 100,000 rows
    IF @I % 100000 = 0
    BEGIN
        PRINT 'Inserted ' + CAST(@I AS VARCHAR(20)) + ' rows so far.'
    END
END

PRINT 'Data insertion complete. Total rows inserted: ' + CAST(@I AS VARCHAR(20))
GO