-- Create table
IF OBJECT_ID('IISLOG','U') IS NULL
BEGIN
CREATE TABLE [IISLOG](
[COOKIE_ID] [int] NOT NULL,
[VISIT_DATE] [date] NOT NULL,
[TRANSACTION_VALUE] [money] NOT NULL
) ON [PRIMARY]
CREATE CLUSTERED INDEX [IX_VISIT_DATE] ON [IISLOG]
( [VISIT_DATE] ASC ) ON [PRIMARY]
END
-- Empty the table
DELETE FROM IISLOG
-- Insert 8 million rows
DECLARE @I INT = 0
DECLARE @HITS INT = 8000000
BEGIN TRANSACTION
WHILE @I<@HITS
BEGIN
INSERT INTO IISLOG(COOKIE_ID,VISIT_DATE,TRANSACTION_VALUE)
SELECT RAND()*@HITS/100 -- COOKIE_ID
,DATEADD(day,CONVERT(INT,(RAND()*365)),'20170801') -- VISIT DATE
,CASE WHEN RAND()<0.01

THEN RAND()*10.0 ELSE 0.0 END -- TRANSACTION_VALUE
SET @I=@I+1
END

COMMIT TRANSACTION